spring:
  data:
    mongodb:
      authentication-database: admin
      host: localhost
      port: 27017
      username: admin
      password: root
      database: cqrs-command
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
