version: '3.9'

services:
  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: "${MONGO_ROOT_USER}"
      MONGO_INITDB_ROOT_PASSWORD: "${MONGO_ROOT_PASSWORD}"
    volumes:
      - "${MONGO_HOME}/data:/data/db"
#    command: mongod --auth --replSet myReplicaSet --bind_ip localhost,mongo1 --keyFile /data/mongodb-keyfile
    command: "mongod --auth"
#
#  mongo2:
#    image: mongo
#    restart: always
#    command: mongod --replSet myReplicaSet --bind_ip localhost,mongo2
#    ports:
#      - "27018:27017"
#    depends_on:
#      - mongo1
#    volumes:
#      - "${MONGO_HOME}/mongo2:/data/db"
#
#  mongo3:
#    image: mongo
#    restart: always
##    command: mongod --replSet myReplicaSet --bind_ip localhost,mongo3
#    ports:
#      - "27019:27017"
#    depends_on:
#      - mongo2
#    volumes:
#      - "${MONGO_HOME}/mongo3:/data/db"

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: "${MONGO_ROOT_USER}"
      ME_CONFIG_MONGODB_ADMINPASSWORD: "${MONGO_ROOT_PASSWORD}"
      ME_CONFIG_MONGODB_URL: "mongodb://${MONGO_ROOT_USER}:${MONGO_ROOT_PASSWORD}@mongo:27017/"
    depends_on:
      - mongo
